- api/page/post.ts
- app/data/getSharedPage.server.ts
- app/data/submitToolRequest.server.ts
- tests/api/page-post.test.ts
Also first pull request on the master repo - ensure that checks succeed.
> Return a better error message when reinviting notebooks happen

- app/routes/__public/blog.tsx
> Fix low contrast text

- package/scripts/test.ts
- scripts/commands/test.ts
> add shell for windows

- app/components/useMarkdownComponent.tsx
- app/data/listMarkdownFiles.server.ts
- app/routes/docs.tsx
- docs/applications/metadata.json
- docs/basics/sharing_pages.md
- docs/developer/data_schema.md
- docs/developer/extension_development.md
- docs/developer/how_to_contribute.md
- docs/metadata.json
> Doc updates

- .gitignore
- .vscode/launch.json
- docs/developer/how_to_contribute.md
> Add launch.json

- app/routes/embeds.tsx
- app/routes/embeds/index.tsx
- chromium/src/components/Popup.tsx
- package/backend/createApiBackendPostHandler.ts
- package/components/HomeDashboardTab.tsx
- package/components/NotificationContainer.tsx
- package/components/RootDashboard.tsx
- package/internal/setupWsFeatures.ts
- tests/package/components/NotificationContainer.test.tsx
> Support logging out within an extension, embeds, and chrome extension

- api/extensions/$id/$file/post.ts
- package-lock.json
- package.json
> Add windows support to APIGatewayProxyHandler

- api/apps/oura/get.ts
@dvargas92495 
relevant docs:
https://cloud.ouraring.com/v2/docs
https://partnersupport.ouraring.com/hc/en-us/articles/19907726838163-Oura-API-V2-Upgrade-Guide
for: https://github.com/RoamJS/oura-ring/pull/6
> Add Oura API 2 endpoint

- .gitignore
- data/main.ts
- data/scripts/agent.ts
- data/scripts/bootstrap.sh
- scripts/commands/plan.ts
Going to start experimenting with an initial MVP for an actual employee. This problem is vast and is a bit hard to project out everything we'll want this to agent to do. So gonna just publish an initial script and start iterating on the box directly.
The create employee action should probably create a box and run the install script, but not focused on onboarding for now.
> Create our initial Agent Loop Script

- app/components/Dialog.tsx
- app/data/fireUserEmployee.server.ts
- app/routes/__private/user/employees.$uuid.tsx
- app/routes/__private/user/notebooks.$uuid.tsx
- package/components/Button.tsx
We're going to be spinning up a lot of test agents, so I wanted to add a way to spin it down and get rid of it. So am starting to build out the fire employee flow.
> Create Fire Employee Dialog

- app/routes/__public/oauth/$id.tsx
- data/schema.ts
for: https://github.com/RoamJS/query-builder/pull/248
> add anon with acces_token check to oauth

- app/routes/__public/oauth/$id.tsx
Now with `?anonymous=true`, we could remove this hack
> Remove roamjs search param

- data/main.ts
This adds the google client secret from the SamePage account both to the monorepo and to the google-samepage repo.
> Expose new google oauth client secret from terraform

- app/routes/__public/oauth/$id.tsx
Reference: https://github.com/samepage-network/github-samepage/pull/3
> Oauth - make installation_id optional

- package-lock.json
- package.json
- package/backend/uploadFileContent.ts
- package/internal/types.ts
- scripts/commands/apply.ts
First commit is about some type changes that other apps can use.
Third commit is about content type changes needed to use the onboarding script
> Make type improvements to the various oauth endpoints we stand up

- app/routes/__private/user/employees.new.tsx
> add simple check/error message

- api/access-token/post.ts
`access-token` api is failing in `prod` but not `dev`
adding logs to get visibility
> add error handling

- api/mocks/aws/post.ts
- app/data/createUserEmployee.server.ts
- app/data/getUserEmployeeProfile.server.ts
- app/data/retrieveUserEmployeePrivateKey.server.ts
- app/routes/__private/user/employees.$uuid.key.tsx
- app/routes/__private/user/employees.$uuid.tsx
- package/backend/mockEmailLocally.server.ts
- package/backend/sendEmail.server.ts
- package/scripts/internal/compile.ts
Surfacing enough info so that we could SSH into the box and start running our onboarding script. Still todo:
- Showing the SSH info in the UI
- Confirm successful connection to the box
- Run onboarding script in box
Intentionally deferring:
- Polling status on employee page
- Defining responsibilities (next)
- Automatically running onboarding script on the box
> Setting up instance stats so that we could connect to our agent

- app/routes/__public/oauth/$id.tsx
added state too while I was at it
> Forgot to add grant type to anonymous version

- data/schema.ts
Needed for google, oauth spec compliant
> Add refresh token column to access tokens table

- package-lock.json
- package.json
- package/internal/unbase64.ts
> unbase fix

- package-lock.json
- package.json
- package/internal/unbase64.ts
Reverts samepage-network/samepage.network#168
> Revert "unbase fix"
